[33mcommit e18f7d3c11c9f01675dd60fa209188e079821a44[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmaster[m[33m, [m[1;31morigin/master[m[33m, [m[1;31morigin/HEAD[m[33m)[m
Author: Abdullahfalak007 <abdullahfalak007@gmail.com>
Date:   Thu Jul 17 00:49:28 2025 +0500

    About Section Completed!

src/assets/images/about_section_background.jpg
src/components/about/About.tsx
src/components/navbar/Navbar.tsx
src/constants/images.ts
src/pages/home/Home.tsx
